.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "April 24, 2024 - Version 5.06"
.SH NAME
sl \- display animations aimed to correct users who accidentally enter sl instead of ls.
.SH SYNOPSIS
.B sl
[
.B \-acdeFlw
]
.SH DESCRIPTION
.B sl
Displays animations aimed to correct users who accidentally enter sl instead of ls.  SL stands for Steam Locomotive.
.PP
.TP
.B \-a
An accident is occurring. People cry for help.
.TP
.B \-c
C51 appears instead of D51.
.TP
.B \-d
Disco mode. Alternate colors during animation.
.TP
.B \-e
Escape. Disallow interrupt by Ctrl+C.
.TP
.B \-F
It flies like the galaxy express 999.
.TP
.B \-s
Shmyaks artillery train.
.TP
.B \-G
It's French like Oscar.
.TP
.B \-<number of wagons>
Specify the number of wagons like `sl -5`.
.TP
.B \-l
Little version.
.TP
.B \-w
Windy day. Locomotive moves faster.
.TP
.B \-v
Prints the version and last updated.
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHOR
Toyoda Masashi (mtoyoda@acm.org)
